import AppKit
@testable import Clipped
import Foundation
import Testing

@MainActor
struct PasteboardIngestionTests {
    // MARK: - PasteboardMonitor

    @Test("Monitor fires onNewItem when changeCount advances")
    func monitorFiresOnChange() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        var captured: [PasteboardMonitor.NewItemEvent] = []
        monitor.onNewItem = { captured.append($0) }

        mock.stageExternalWrite(types: [.string], strings: [.string: "hello"])
        monitor.check()

        #expect(captured.count == 1)
        #expect(captured.first?.item.plainText == "hello")
        #expect(captured.first?.hasConcealedType == false)
    }

    @Test("Monitor does not re-emit when changeCount unchanged")
    func monitorSkipsWhenUnchanged() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        var captured = 0
        monitor.onNewItem = { _ in captured += 1 }

        mock.stageExternalWrite(types: [.string], strings: [.string: "hello"])
        monitor.check()
        monitor.check()
        monitor.check()

        #expect(captured == 1)
    }

    @Test("Monitor skips org.nspasteboard.TransientType content")
    func monitorSkipsTransient() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        var captured = 0
        monitor.onNewItem = { _ in captured += 1 }

        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        mock.stageExternalWrite(types: [transient, .string], strings: [.string: "ignore me"])
        monitor.check()

        #expect(captured == 0)
    }

    @Test("Monitor skips org.nspasteboard.AutoGeneratedType content")
    func monitorSkipsAutoGenerated() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        var captured = 0
        monitor.onNewItem = { _ in captured += 1 }

        let autoGen = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        mock.stageExternalWrite(types: [autoGen, .string], strings: [.string: "ignore me"])
        monitor.check()

        #expect(captured == 0)
    }

    @Test("Monitor flags ConcealedType so downstream can mark the item sensitive")
    func monitorFlagsConcealed() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        var captured: [PasteboardMonitor.NewItemEvent] = []
        monitor.onNewItem = { captured.append($0) }

        mock.stageExternalWrite(
            types: [concealedPasteboardType, .string],
            strings: [.string: "supersecret"]
        )
        monitor.check()

        #expect(captured.count == 1)
        #expect(captured.first?.hasConcealedType == true)
    }

    @Test("Monitor.write advances the change-count baseline so the next poll is a no-op")
    func monitorWriteBumpsBaseline() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        var captured = 0
        monitor.onNewItem = { _ in captured += 1 }

        monitor.write { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("our own write", forType: .string)
        }
        monitor.check()

        #expect(captured == 0)
    }

    @Test("Monitor prefers PNG data over TIFF when both are present")
    func monitorPrefersPNG() {
        let mock = MockPasteboard()
        let monitor = PasteboardMonitor(pasteboard: mock)

        let pngMagic: [UInt8] = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]
        // A 1x1 PNG so NSImage(data:) succeeds.
        let onePixelPNG = Data([
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
            0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
            0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
            0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4,
            0x89, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x44, 0x41,
            0x54, 0x78, 0x9C, 0x63, 0x00, 0x01, 0x00, 0x00,
            0x05, 0x00, 0x01, 0x0D, 0x0A, 0x2D, 0xB4, 0x00,
            0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE,
            0x42, 0x60, 0x82,
        ])
        // TIFF sentinel — monitor should ignore this because PNG is preferred.
        let tiffSentinel = Data([0x54, 0x49, 0x46, 0x46])

        var captured: ClipboardItem?
        monitor.onNewItem = { captured = $0.item }

        mock.stageExternalWrite(
            types: [.png, .tiff],
            data: [.png: onePixelPNG, .tiff: tiffSentinel]
        )
        monitor.check()

        guard case let .image(data, _) = captured?.content else {
            Issue.record("Expected image content, got \(String(describing: captured?.content))")
            return
        }
        #expect(data.prefix(pngMagic.count).elementsEqual(pngMagic))
    }

    // MARK: - End-to-end through ClipboardManager

    @Test("Dedup: copying the same text twice produces one entry at the top")
    func dedupThroughFullPipeline() {
        let mock = MockPasteboard()
        let manager = ClipboardManager(pasteboard: mock)
        manager.stopMonitoring()
        let settings = MockSettingsManager()
        settings.persistAcrossReboots = false
        manager.settingsManager = settings
        manager.historyStore = MockHistoryStore()

        mock.stageExternalWrite(types: [.string], strings: [.string: "dupe"])
        manager.monitor.check()

        mock.stageExternalWrite(types: [.string], strings: [.string: "dupe"])
        manager.monitor.check()

        #expect(manager.items.count == 1)
        #expect(manager.items.first?.plainText == "dupe")
    }

    @Test("copyToClipboard writes through the injected pasteboard")
    func copyWritesThroughInjectedPasteboard() {
        let mock = MockPasteboard()
        let manager = ClipboardManager(pasteboard: mock)
        manager.stopMonitoring()
        let settings = MockSettingsManager()
        manager.settingsManager = settings
        manager.historyStore = MockHistoryStore()

        let item = ClipboardItem(content: .text("copy me"), contentType: .plainText)
        manager.copyToClipboard(item)

        #expect(mock.string(forType: .string) == "copy me")
    }
}
