import AppKit
import Foundation
import Observation
import os

private let codeEditorBundleIDs: Set<String> = [
    "com.microsoft.VSCode",
    "com.apple.dt.Xcode",
    "com.sublimetext.4",
    "com.jetbrains.intellij",
    "dev.zed.Zed",
    "com.todesktop.230313mzl4w4u92", // Cursor
]

private let terminalBundleIDs: Set<String> = [
    "com.apple.Terminal",
    "com.googlecode.iterm2",
    "io.alacritty",
    "com.github.wez.wezterm",
    "net.kovidgoyal.kitty",
]

/// Industry-standard pasteboard types set by apps to flag content that should be skipped.
/// See https://nspasteboard.org
let concealedPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
private let legacyTransientType = NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")

private let skippableNSPasteboardTypes: Set<NSPasteboard.PasteboardType> = [
    transientType,
    autoGeneratedType,
    legacyTransientType,
]

/// Polls `NSPasteboard.general` for new content and emits raw `ClipboardItem`s via its
/// `onNewItem` callback. Knows nothing about history, mutation, persistence, or UI —
/// its sole job is "something changed on the pasteboard; here's a structured item."
@MainActor
@Observable
final class PasteboardMonitor {
    private static let logger = Logger(subsystem: "com.mcclowes.clipped", category: "PasteboardMonitor")

    /// Event payload handed to the pipeline.
    struct NewItemEvent {
        let item: ClipboardItem
        let bundleID: String?
        let hasConcealedType: Bool
    }

    private(set) var isMonitoring = false

    /// Invoked on the main actor whenever the monitor observes new pasteboard content.
    var onNewItem: ((NewItemEvent) -> Void)?

    let pasteboard: PasteboardProtocol
    private var pollTimer: Timer?
    private var lastChangeCount: Int

    private static let pollInterval: TimeInterval = 0.5

    init(pasteboard: PasteboardProtocol = NSPasteboard.general) {
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Lifecycle

    func startMonitoring() {
        guard !isMonitoring else { return }
        Self.logger.debug("Starting clipboard monitoring")
        isMonitoring = true
        pollTimer = Timer.scheduledTimer(withTimeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.check()
            }
        }
    }

    func stopMonitoring() {
        Self.logger.debug("Stopping clipboard monitoring")
        isMonitoring = false
        pollTimer?.invalidate()
        pollTimer = nil
    }

    /// Re-baseline to the current pasteboard state. Call after initial history load so
    /// the pasteboard content at launch is not treated as a new copy.
    func resetBaseline() {
        lastChangeCount = pasteboard.changeCount
    }

    /// Write to the pasteboard without triggering our own monitoring as a new copy.
    /// Updates the change-count high-water mark so the next poll ignores our own write.
    func write(_ body: (PasteboardProtocol) -> Void) {
        body(pasteboard)
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Polling

    /// Run one poll cycle. Exposed as `internal` so tests can drive the monitor deterministically
    /// without waiting for the `Timer`.
    func check() {
        // MainActor is serial; no re-entrancy guard needed.
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // Skip content flagged by nspasteboard.org convention as transient or auto-generated.
        let types = pasteboard.types ?? []
        if types.contains(where: { skippableNSPasteboardTypes.contains($0) }) {
            return
        }

        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let bundleID = frontmostApp?.bundleIdentifier
        let hasConcealedType = types.contains(concealedPasteboardType)

        guard let item = readClipboardItem(
            appName: frontmostApp?.localizedName,
            bundleID: bundleID
        ) else { return }

        onNewItem?(NewItemEvent(
            item: item,
            bundleID: bundleID,
            hasConcealedType: hasConcealedType
        ))
    }

    // MARK: - Parsing

    private func readClipboardItem(
        appName: String?,
        bundleID: String?
    ) -> ClipboardItem? {
        let types = pasteboard.types ?? []

        // Check for image first
        if types.contains(.tiff) || types.contains(.png) {
            if let imageData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
                if let image = NSImage(data: imageData) {
                    return ClipboardItem(
                        content: .image(imageData, image.size),
                        contentType: .image,
                        sourceAppName: appName,
                        sourceAppBundleID: bundleID
                    )
                }
            }
        }

        // Check for URL
        if types.contains(.URL), let url = URL(string: pasteboard.string(forType: .string) ?? "") {
            if url.scheme == "http" || url.scheme == "https" {
                return ClipboardItem(
                    content: .url(url),
                    contentType: .url,
                    sourceAppName: appName,
                    sourceAppBundleID: bundleID
                )
            }
        }

        // Check for rich text
        if types.contains(.rtf), let rtfData = pasteboard.data(forType: .rtf) {
            let plainText = pasteboard.string(forType: .string) ?? ""
            return ClipboardItem(
                content: .richText(rtfData, plainText),
                contentType: .richText,
                sourceAppName: appName,
                sourceAppBundleID: bundleID
            )
        }

        // Plain text / code
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            // Detect URLs pasted as plain text (no .URL pasteboard type)
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.contains(" "), !trimmed.contains("\n"),
               let url = URL(string: trimmed),
               url.scheme == "http" || url.scheme == "https"
            {
                return ClipboardItem(
                    content: .url(url),
                    contentType: .url,
                    sourceAppName: appName,
                    sourceAppBundleID: bundleID
                )
            }

            let isFromCodeEditor = bundleID.map { codeEditorBundleIDs.contains($0) } ?? false
            let isFromTerminal = bundleID.map { terminalBundleIDs.contains($0) } ?? false
            let isDevContent = isFromCodeEditor || isFromTerminal
                || DeveloperContentDetector.isDeveloperContent(string)
            return ClipboardItem(
                content: .text(string),
                contentType: .plainText,
                sourceAppName: appName,
                sourceAppBundleID: bundleID,
                isDeveloperContent: isDevContent
            )
        }

        return nil
    }
}
